apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes for an Apache Derby  instance for a  simple WAS Liberty app
name: apache-derby
version: 1.0
maintainers:
  - name: David Carew
    email: carew@us.ibm.com
